# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/nwd_acc_design/nwd_acc_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nwd_acc_design || ORIG_REF_NAME==nwd_acc_design} -quiet] -quiet

# IP: bd/nwd_acc_design/ip/nwd_acc_design_processing_system7_0_0/nwd_acc_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nwd_acc_design_processing_system7_0_0 || ORIG_REF_NAME==nwd_acc_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/nwd_acc_design/ip/nwd_acc_design_nwd_acc_ip_0_0/nwd_acc_design_nwd_acc_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nwd_acc_design_nwd_acc_ip_0_0 || ORIG_REF_NAME==nwd_acc_design_nwd_acc_ip_0_0} -quiet] -quiet

# IP: bd/nwd_acc_design/ip/nwd_acc_design_ps7_0_axi_periph_0/nwd_acc_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nwd_acc_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==nwd_acc_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/nwd_acc_design/ip/nwd_acc_design_rst_ps7_0_100M_0/nwd_acc_design_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nwd_acc_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==nwd_acc_design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/nwd_acc_design/ip/nwd_acc_design_auto_pc_0/nwd_acc_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nwd_acc_design_auto_pc_0 || ORIG_REF_NAME==nwd_acc_design_auto_pc_0} -quiet] -quiet

# XDC: bd/nwd_acc_design/nwd_acc_design_ooc.xdc
